version: "3.8"

services:
  backend:
    container_name: Mower-Backend-Production
    build:
      context: .
      dockerfile: ./app/Dockerfile
      target: production
    command: npm run start:prod
    env_file:
      - ./app/.env
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./app:/usr/src/app
